FROM localhost:5000/test/c:1
#		test/fixtures/d/Dockerfile  0.06.20  2018-05-19_09:30:38_CDT  https://github.com/BradleyA/Search-docker-registry-v2-script.2.0.git  uthree  three.cptx86.com 0.05  
#		   inital commit 

RUN mkdir -p test && touch test/d

CMD ["sh"]
